### ISSUE TITLE
Clarification of Administrator Requirement

### ISSUE THREAD

**Issue by JyeGuru** [AriAlavi/rimlink#1]
It does not appear that there is any requirement for running as administrator, and this prevents having this app run via a launch script on a Portable Rimworld folder.

Would it be possible to clarify exactly what the requirement for running as administrator is, so I can look into patching this and allowing a command-line switch to remove the requirement?

**Comment by AriAlavi** [comment]
Administrator requirement is in place because Steam's installation is often in Program Files (x86). This is treated as a special directory by Windows and admin permission is required to create and delete folders. The administrator requirement is required at all times as a lazy method of preventing problems with this. 

It could be made conditional by either checking if the path includes Program Files (x86), or for maximum compatibility, attempting to create and delete a folder, if failing, then require administrator privileges.

**Comment by JyeGuru** [comment]
Thanks for the response! That makes sense, and I can see why this has been set as the default. A simple option to "ignore not running as admin" for advanced users would be fantastic though, both for convenience and security.

I'm not great with Python, but I think I can patch in an environment variable check to short-circuit `isAdmin()` without too much drama: https://github.com/AriAlavi/rimlink/blob/master/rimlink.py#L16 - I'll see if I can find some time over the next couple of weeks to do so.

**Comment by Coffee-fueled-deadlines** [comment]
@JyeGuru added a pull request that should allow this.
